[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*.ics"
  [headers.values]
    Content-Type = "text/calendar; charset=utf-8"
